name: Download Annual Reports from CSV

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests aligo

    - name: Run download script
      env:
        ALIYUN_REFRESH_TOKEN: ${{ secrets.ALIYUN_REFRESH_TOKEN }}
        ALIYUN_FOLDER_ID: ${{ secrets.ALIYUN_FOLDER_ID }}
      run: python main.py
